input:
  arrival_time: 0.5
  healthyfile: /media/raymond/429D-D132/testing_timesteps/2//tissue_previous_step//perfusion.xdmf
  mesh_file: /media/raymond/429D-D132/testing_timesteps/2/bf_sim/clustered_mesh.xdmf
  recovery_time: 0
  strokefile: /media/raymond/429D-D132/testing_timesteps/2//tissue_current_step//perfusion.xdmf
  treatmentfile: /media/raymond/429D-D132/testing_timesteps/2//tissue_current_step//perfusion.xdmf
output:
  res_fldr: /media/raymond/429D-D132/testing_timesteps/2//feedback/
  time_series: false
parameter:
  core_threshold: 0.8
  kb: 0.00215699
  kf: 0.00044719
  ks1: 0.175
  ks2: -3.304
  kt: 0.00039441
  perfusion_gm_wm: 2.6998
  tissue_timestep_seconds: 60
