input:
  # inlet boundary condition, Dirichlet (DBC) or Neumann (NBC) or mixed
  # for mixed option inlet_boundary_file is needed and read_inlet_boundary=true
  # considered only when read_inlet_boundary = false
  # otherwise determined based on the inlet boundary file
  inlet_BC_type: mixed
  # file specifying inlet boundary conditions
  inlet_boundary_file: ./verification/verification_coupled/bf_sim/boundary_condition_file.csv
  # mesh file path
  mesh_file: ./verification/verification_mesh/labelled_box_mesh.xdmf
  # path of folder containing pre-computed permeability tensor form 
  permeability_folder: ./verification/verification_mesh/
  # read inlet boundary file (no-false or yes-true)
  read_inlet_boundary: true
output:
  # compute pre-determined averages (no-false or yes-true, old implementations)
  comp_ave: false
  # path of the folder storing results
  res_fldr: ./verification/verification_mesh/results/
  # list of saved variables including any of the following
  # {'beta12','beta23','K1','K2','K3','perfusion','press1','press2','press3','vel1','vel2','vel3'}
  res_vars: {'press1','vel1','perfusion','beta12','beta23'}
  # list of integral variables based on the list of saved variables, examples:
  # press1_surfint --> surface integral of the arteriole pressure
  # perfusion_voluave --> volume-averaged perfusion = total flow
  # vel1_surfint --> surface integral of the arteriole velocity = inlet volumetric flow rate
  # vel1_magn_voluint --> volume integral of the arteriole velocity magnitude
  integral_vars: {'vel1_surfint','press1_surfave','perfusion_voluave'}
physical:
  # arteriole permeability magnitude [mm^3 s g^-1]
  K1gm_ref: 1.234e-6
  # capillary permeability magnitude [mm^3 s g^-1]
  K2gm_ref: 1.0
  # venule permeability magnitude [mm^3 s g^-1]
  K3gm_ref: 1.0
  # arteriole-capillary coupling coefficient [Pa^-1 s^-1]
  beta12gm: 0.000002
  # capillary-venule coupling coefficient [Pa^-1 s^-1]
  beta23gm: 0.000002
  # GM/WM coupling coefficient ratio 
  gmowm_beta_rat: 2.50
  # GM/WM permeability ratio 
  gmowm_perm_rat: 1.0
  # arteriole pressure, applied only when read_inlet_boundary = false [Pa]
  p_arterial: 10000.0
  # fixed venous pressure [Pa]
  p_venous: 0.0
simulation:
  # finite element approximation order used for the pressure field
  fe_degr: 2
  # model type --> 1 arteriole compartment ('a'); arteriole-capillary-venule compartments ('acv')
  model_type: 'a'
  # finite element approximation order used for the velocity field
  vel_order: 1
  cpld_conv_crit: 1.0e-4
  coupled_model: true
optimisation:
  # parameters to be optimised to match pre-defined perfusion values
  parameters: ['gmowm_beta_rat','K1gm_ref']
  # random initialisation for optimisation
  random_init: true
  # range for initial parameters, applied only when random_init = true
  init_param_range: [[0.1,10],[0.0001,0.01]]
  # minimum perfusion target [ml/min/100ml]
  Fmintarget: 10.0
  # maximum perfusion target [ml/min/100ml]
  Fmaxtarget: 80.0
  # GM perfusion target [ml/min/100ml]
  FGtarget: 56.0
  # WM perfusion target [ml/min/100ml]
  FWtarget: 21.0
  # optimisation method, options available based on scipy.optimize
  method: 'Nelder-Mead'
